version: '2'
services:
  # web: takes Dockerfile when running docker-compose up
  web:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    command: "npm run dev"
    volumes:
      - .:/opt/app
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    ports:
      - "6381:6379"
      # Port 6379 is used within the container, use that in your .env file
      # Port 6381 is opened on your host.
      # Use port 6381 to connect by using a Redis client like Medis
